spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        ## 集群名称:上海
        cluster-name: wuhan
        weight: 50
  application:
    name: webclient-provider
server:
  port: 0
