spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.222:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    ## # 配置分库策略
    sharding:
      binding-tables: t_user
      tables:
        t_user:
          key-generator:
            column: id
            type: SNOWFLAKE
          actual-data-nodes: m1.t_user_$->{1..2}
          # 配置 分片算法
          table-strategy:
            standard:
              sharding-column: id
              #
              precise-algorithm-class-name: com.demo.shardingjdbc.MyPreciseTable
              range-algorithm-class-name: com.demo.shardingjdbc.MyRangeTable
#            inline:
#              ## 分片键
#
#              ## 分片算法
#              algorithm-expression: t_user_${(id % 2)+1}
    props:
      sql:
        show: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
