server:
  port: 0

spring:
  application:
    name: openfeign-consumer
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: wuhan
logging:
  level:
    com.demo.cloud.openfeign.consumer.client: debug
feign:
  client:
    config:

