spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.0.3.5:36895/maker_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true&autoReconnect=true
          username: maker_dev
          password: O9WBzQDYczhJIstg
        test2_master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.0.3.5:36895/maker_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true&autoReconnect=true
          username: maker_dev
          password: O9WBzQDYczhJIstg
  main:
    allow-bean-definition-overriding: true

# mybatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml
server:
  port: 6666