server:
  port: 0

spring:
  application:
    name: openfeign-consumer
  cloud:
    nacos:
      # server-addr: 192.168.2.223:8848
      # server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        cluster-name: wuhan
