server:
  port: 0

spring:
  application:
    name: openfeign-consumer
  cloud:
    nacos:
<<<<<<< HEAD:cloud/resttemplate/service-consumer/src/main/resources/application.yml
     # server-addr: 192.168.2.223:8848
     # server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
=======
      server-addr: localhost:8848
      discovery:
        cluster-name: wuhan
>>>>>>> origin/master:cloud-alibaba/resttemplate/service-consumer/src/main/resources/application.yml
