dubbo:
  application:
    registry: nacos://180.163.98.12:8848
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-provider
server:
  port: 8007
spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 180.163.98.12:8848

