dubbo:
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.test.dubbo.provider
server:
  port: 8006
spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 180.163.98.12:8848
        cluster-name: shanghai

