spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: luyi123
      url: jdbc:mysql://180.163.98.12:3306/t_auth1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource