spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      ##默认的数据源
      primary: 主业务数据源名称
      datasource:
        主业务数据源名称:
          username: xxx
          password: xxx
          url: xxx
        另外一个数据源名称:
          username: xxx
          password: xxx
          url: xxx


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
