spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: luyi
    password: 123456
    listener:
      simple:
        ## 手动签收
        acknowledge-mode: manual
        prefetch: 10
        batch-size:
    virtual-host: test
    publisher-confirm-type: simple
    publisher-returns: true
